### PR TITLE
Better image type support

### PR DESCRIPTION
**Pull request by odedniv**
* Get real image type from content.
* Favor quality option over format.
* Don't ruin quality twice when resizing by outputting a PNG buffer.

### CODE REVIEW

**Comment by odedniv** [comment]
@ysugimoto before we go around fixing the failing test (which is due to changing logic), what do you think about the solution, implementation, and logic?

**Comment by ysugimoto** [comment]
@odedniv Ah, sorry I'm late. It looks good. so please pass the test (failings seems to check extension).

**Comment by odedniv** [comment]
@ysugimoto done (I dunno if you get an update, please let me know for future)

**Comment by ysugimoto** [comment]
Thank you for your improvement!

**Pull request merged**
