### PR TITLE
Directory parameter extension - Path Template

### PR DESCRIPTION
**Pull request by kdybicz**
* Introducing output directory extension using Path Template
* Splitting tests groups into separate ones
* Upgrading ava dependency to 0.18.2
* Updating configtest (in progress)
* Updating README.md (in progress)

### CODE REVIEW

**Comment by kdybicz** [comment]
It looks like we are ready for final review. Let me know if you have any comments.

**Comment by ysugimoto** [comment]
Looks good, let's merge this and close https://github.com/ysugimoto/aws-lambda-image/pull/114

**Comment by kdybicz** [comment]
I will prepare for merging. As for #114 I would like to introduce it as alternative to `directory` and `template`, as third, even more advanced option. But I would like to do that later, so if you are ok, I would like to leave #114 open for now.

**Comment by ysugimoto** [comment]
It's OK.

**Pull request merged**
